en:
  advanced:
    water:
      questionnaire:
        options_for_sanitationwater_exists:
          neither: Neither
          existing: Existing
          planned: Planned
          unknown: Don't know
        water_system_exists:
          label: Est-ce que le système d'eau existe déjà ou est-ce qu'il est en projet?
          placeholder: Sélectionnez une option
          tooltip: 'Si vous fournissez des données de coûts réels pour un système existant, choisissez "Existant".'
        area_type:
          label: Description de la zone
          placeholder: Sélectionnez de la zone
          tooltip: Sélectionnez de la zone
        population_density:
          label: Quelle est la densité de population de la zone de service?
          placeholder: 2000
        service_management:
          label: Quelle option décrit le mieux le mode de gestion du service?
          tooltip: Vous pouvez sélectionner plusieurs options.
        construction_financier:
          label: Par qui est financée la construction du système d'eau?
          tooltip: Vous pouvez sélectionner plusieurs options.
        infrastructure_operator:
          label: Qui est le propriétaire légal du système d'approvisionnement en eau?
          tooltip: Vous pouvez sélectionner plusieurs options.
        service_responsbility:
          label: Qui est responsable d'assurer le fonctionnement et l'entretien du système?
          tooltip: Vous pouvez sélectionner plusieurs options.
        standard_enforcer:
          label: Qui est/sera responsable de la surveillance et de l'application des normes de service en vigueur?
          tooltip: Vous pouvez sélectionner plusieurs options.
        rehabilitation_cost_owner:
          label: Qui assume les coûts de renouvellement lorsqu'une réhabilitation du système est nécessaire?
          tooltip: Vous pouvez sélectionner plusieurs options.
        annual_household_income:
          label: Quel est le revenu annuel moyen d'un ménage dans la zone de service?
          placeholder: 600
          tooltip: Ces données sont utilisées pour évaluer l'accessibilité financière et elles peuvent être modifiées pour analyser l'accessibilté par rapport à différents niveaux de richesse dans la zone de service.
        household_size:
          label: Taille moyenne d'un ménage
          placeholder: 6
          tooltip: Il s'agit d'une approximation de la taille moyenne des ménages utilisée pour calculer l'accessibilité financière des services d'eau.
        supply_system_technologies:
          label: Quel est le système utilisé pour fournir le service d'eau? (plusieurs réponses possibles)
          placeholder: Type de technologie.
          tooltip: Type de technologie.
        systems_number:
          label: Nombre de systèmes?
          placeholder: 5
          tooltip: Ces données sont utilisées  pour calculer le coût d'un système unique.
        system_population_design:
          label: Combien de personnes au total les systèmes d'eau sont-ils censés desservir dans cette zone de service?
          placeholder: 20
          tooltip: S'il vous plaît entrer dans la population le système(s) est conçu pour servir.
        system_population_actual:
          label: Combien de personnes au total est-ce que les systèmes d'eau desservent effectivement dans cette zone de service?
          placeholder: 30
          tooltip: S'il vous plaît entrer dans la population le système(s) sert en fait.
        water_source:
          label: Quelle est la source de l'eau?
          placeholder: Sélectionnez une source d'eau
          tooltip: Sélectionnez une source d'eau.
        surface_water_primary_source:
          label: Si de l'eau de surface, de définir la source primaire
          placeholder: Sélectionnez une source primaire
          tooltip: S'il vous plaît sélectionner une source primaire
        water_treatment:
          label: Comment l'eau est habituellement traitée?
          tooltip: Vous pouvez sélectionner plusieurs options.
        power_supply:
          label: Type d'alimentation
          tooltip: Vous pouvez sélectionner plusieurs options.
        distribution_line_length:
          label: Longueur de lien de distribution (km)
          placeholder: 200
          tooltip: S'il vous plaît indiquer la longueur de la liaison de distribution.
        capital_costs:
          capital_costs: Coûts d'investissement
          recurring_costs: Coûts récurrents
        #aggregate_actual_hardware_expenditure:
        #  label: What has been/will be the actual expenditure on capital expenditure (hardware) and how long is/was the system expected to last at the time of construction (the useful lifespan) or detail disaggregated below?
        #  tooltip:
        actual_hardware_expenditure:
          label: Quelle est la capitale de matériel de dépenses totales sur la zone de service pour construire les systèmes?
          placeholder: 5000
          tooltip: Le capital investi dans la construction ou l'achat d'actifs fixes, tels que les structures en béton, pompes et canalisations. 
        system_lifespan_expectancy:
          label: Combien de temps est un système prévu pour durer à partir du moment de la construction (la durée de vie utile)?
          placeholder: 30
          tooltip: Veuillez fournir les dépenses pour toute la zone de service. Si vous ne connaissez que le coût moyen par système, veuillez multiplier celui-ci par le nombre de systèmes.
        actual_software_expenditure:
          label: Quel est le coût total en investissement immatériel pendant la construction des systèmes dans la zone de service?
          placeholder: 3000
          tooltip: "Coût des activités ponctuelles avec les  parties prenantes avant la construction ou la mise en œuvre, l'amélioration ou l'extension (y compris le coût des activités ponctuelles de développement des capacités). Veuillez fournir les dépenses pour toute la zone de service. Si vous ne connaissez que le coût moyen par système, veuillez multiplier celui-ci par le nombre de systèmes."
        unpaid_labour:
          label: Est-ce que les ménages ou la communauté ont contribué de la main-d'oeuvre non rémunérée pour mettre en place les systèmes?
          placeholder: Sélectionnez une option
          tooltip: Sélectionnez une option
        minor_operation_expenditure:
          label: Quel est le coût d'exploitation et de maintenance par an?
          placeholder: 1000
          tooltip: Dépenses pour le fonctionnement et l'entretien: elles comprennent en général les dépenses récurrentes telles que la main-d’œuvre, le carburant, les produits chimiques, les matériaux, et l'achat d'eau en gros. Veuillez fournir les dépenses pour toute la zone de service. Si vous ne connaissez que le coût moyen par système, veuillez multiplier celui-ci par le nombre de systèmes.
        capital_maintenance_expenditure:
          label: Quel est le coût moyen de renouvellement ou de réhabilitation par an? 
          placeholder: 400
          tooltip: "Renouvellement des actifs et coût de remplacement: les coûts occasionnels et irréguliers qui visent à rétablir la fonctionnalité d'un système, comme le remplacement de la tige de pompe ou du clapet de pied dans les pompes manuelles, ou du générateur diesel dans les systèmes motorisés. Comme les dépenses pour le renouvellement sont par définition peu fréquentes, elles ne sont pas forcément engagées tous les ans. Si vous utilisez des données réelles, vous pouvez indiquer la moyenne des dépenses des 5 dernières années. Veuillez indiquer les dépenses pour toute la zone de service. Si vous ne connaissez que le coût moyen par système, veuillez multiplier celui-ci par le nombre de systèmes."
        loan_cost:
          label: Quel est le coût du capital d'un éventuel emprunt contracté pour financer le service?
          placeholder: 6000
          tooltip: "Veuillez indiquer le coût moyen de l'emprunt, par exemple le montant des intérêts. Veuillez fournir les dépenses pour toute la zone de service. Si vous ne connaissez que le coût moyen par système, veuillez multiplier celui-ci par le nombre de systèmes."
        loan_payback_period:
          label: Quelle est la durée d'amortissement de cet emprunt?
          placeholder: 20
          tooltip: Veuillez fournir la durée moyenne pour le remboursement de l'emprunt.
        direct_support_cost:
          label: Qu'est-ce qui a été dépensé /sera dépensé pour l'appui direct?
          placeholder: 10
          tooltip: Veuillez fournir les dépenses par personne/ par an. L'appui direct est un appui structuré pour les fournisseurs de services et les utilisateurs ou groupes d'utilisateurs et se rapporte à l'exploitation et la gestion d'un service WASH. Les coûts d'appui directs couvrent les activités de surveillance, le conseil technique et le soutien administratif, organisationnel ou juridique. Les coûts d'appui avant et pendant la construction du capital d'un projet ne sont pas inclus, car ceux-ci sont considérés comme investissement immatériel. L'appui direct est souvent utilisé comme synonyme de «appui post-construction ».
        indirect_support_cost:
          label: Qu'est-ce qui a été dépensé /sera dépensé pour l'appui indirect?
          placeholder: 2
          tooltip: Veuillez fournir les dépenses par personne/ par an. Les coûts d'appui indirects couvrent les dépenses d'appui au niveau macro, pour la planification et l'élaboration des politiques sectorielles, et l'appui aux autorités de services décentralisés ou le gouvernement local. L'appui indirect comprend le renforcement des capacités des professionnels et des techniciens et l'appui aux capacités de des autorités locales, pour se mettre en conformité avec les normes et directives nationales.
        service_levels:
          label: S'il vous plaît définir jusqu'à quatre niveaux de service pour les utilisateurs du système d'eau
          tooltip: S'il vous plaît définir jusqu'à quatre niveaux de service
        service_level_name:
          label: Name the service level
          placeholder: Nommez le niveau de service
        service_level_share:
          label: Part du niveau de service
          placeholder: 25%
        national_accessibility_norms:
          label: Est-ce que l'accessibilité du service est conforme aux normes nationales?
          placeholder: Sélectionnez une option
          tooltip: Sélectionnez une option.
        national_quantity_norms:
          label: Est-ce que la quantité fournie par le service est conforme aux normes nationales?
          placeholder: Sélectionnez une option
          tooltip: Sélectionnez une option.
        national_quality_norms:
          label: Est-ce que la qualité de l'eau est conforme aux normes nationales?
          placeholder: Sélectionnez une option
          tooltip: Sélectionnez une option.
        national_reliability_norms:
          label: Est-ce que la fiabilité du service est conforme aux normes nationales?
          placeholder: Sélectionnez une option
          tooltip: Sélectionnez une option.
      report:
        final_report: Eau Avancée | Rapport Final
