en:
  advanced:
    shared:
      dont_know: Don't know
      country:
        label: Country?
        placeholder: Select a country
        tooltip: Please select the country in which the service is located.
      currency:
        label: Currency?
        placeholder: Select a currency
        tooltip: Please choose a currency for the cost calculations.
      year_of_expenditure:
        label: Year of expenditure?
        placeholder: Select a year
        tooltip: 'When inputting costs, expenditure made in other years or currencies should be converted to this currency and base year. See the WASHCost training and the example currency converter here: http://www.washcost.info/page/2521'
      region:
        label: Region?
        placeholder: Calabria
        tooltip: Please select the region in which the service is located.
      town:
        label: City/Town name?
        placeholder: Catanzaro
        tooltip: Please select the city/town in which the service is located.
      technology_choice_required: A choice of at least one technology is required
