en:
  advanced:
    sanitation:
      questionnaire:
        options_for_area_type:
          rural: Rural
          small_town: Small town
          peri_urban: Peri-urban
          urban: Urban
          mixed: Mixed
          unknown: Dont know
        sanitation_service_exists:
          label: Does the sanitation service already exist or is it planned?
          placeholder: Select an option
          tooltip: The tip
        area_type:
          label: Description of area type
          placeholder: Select an area type
          tooltip: The tip
        service_management:
          label: Which of these options best describes how the sanitation service is managed?
        construction_financier:
          label: Who finances the construction of the sanitation system?
        infrastructure_operator:
          label: Who legally owns the sanitation infrastructure?
        standard_enforcer:
          label: Who has/will have responsibility for checking and enforcing the standard of sanitation services?
        rehabilitation_cost_owner:
          label: Who covers the cost of rehabilitation when larger repairs are needed (pit tank emptying)?
        supply_system_technologies:
          label: What are the typical household latrine types in your service delivery area?
          placeholder: Choose a technology
          tooltip: The tip
        systems_number:
          label: How many latrines are there?
          placeholder: 5
          tooltip: The tip
        system_population_design:
          label: How many people are these latrine(s) designed to serve?
          placeholder: 20
        system_population_actual:
          label: How many people do these latrine(s) actually serve?
          placeholder: 30
        aggregate_actual_hardware_expenditure:
          label: What is the total expenditure on capital hardware over the service area to construct the latrines? How long is the latrine expected to last from the time of construction (eg. useful lifespan)?
        actual_hardware_expenditure:
          label: Cost
          placeholder: 5000
          tooltip: Tip here
        system_lifespan_expectancy:
          label: Useful lifespan (years)
          placeholder: 30
          tooltip: Tip here
        direct_support_cost:
          label: What has been/will be expenditure on direct support per person per year?
          placeholder: 10
          tooltip: The tip
        indirect_support_cost:
          label: What has been/will be expenditure on indirect support per person per year?
          placeholder: 2
          tooltip: The tip
        annual_household_income:
          label: What is the average annual household income in the service area?
          placeholder: 600
          tooltip: The tip
        household_size:
          label: Average household size
          placeholder: 6
          tooltip: The tip
        actual_software_expenditure:
          label: What is the total expenditure on capital expenditure software over the service area during or prior to construction?
          tooltip: The tip
          placeholder: 3000
        unpaid_labour:
          label: Has there been any volunteer or unpaid labour been by the household or community?
          placeholder: Select an option
          tooltip: Tip here
        minor_operation_expenditure:
          label: What has been/will be the minor operation expenditure?
          placeholder: 1000
          tooltip: Tip here
        capital_maintenance_expenditure:
          label: What has been/will be spent on capital maintenance expenditure?
          placeholder: 400
          tooltip: Tip here
        loan_cost:
          label: What is the cost servicing any loans taken to fund the service?
          placeholder: 6000
          tooltip: Tip here
        loan_payback_period:
          label: What is the payback period on this loan?
          placeholder: 20
          tooltip: Tip here
        service_levels:
          label: Please define upto four service levels for users of the sanitation service
          tooltip: The tip
        service_level_name:
          label: Name the service level
          placeholder: Service level name
        service_level_share:
          label: Service level share
          placeholder: 25%
          tooltip: The tip
        national_accessibility_norms:
          label: Does the service accessibility meet the national norms?
          placeholder: Select an option
          tooltip: The tip
        national_use_norms:
          label: Does the service use meet the national norms?
          placeholder: Select an option
        national_environmental_protection_norms:
          label: Does the service environtmental protection meet the national norms?
          placeholder: Select an option
        national_reliability_norms:
          label: Does the service reliability meet the national norms?
          placeholder: Select an option
          tooltip: The tip
      report:
        final_report: Advanced Sanitation | Final Report