en:
  advanced:
    sanitation:
      questionnaire:
        sanitation_service_exists:
          label: Does the sanitation service already exist or is it planned?
          placeholder: Select an option
          tooltip: 'If you are providing real cost data on an existing system, please choose "Existing".'
        area_type:
          label: Description of area type
          placeholder: Select an area type
          tooltip: Please select an area type
        service_management:
          label: Which of these options best describes how the sanitation service is managed?
        construction_financier:
          label: Who finances the construction of the sanitation system?
        infrastructure_operator:
          label: Who legally owns the sanitation infrastructure?
        standard_enforcer:
          label: Who has/will have responsibility for checking and enforcing the standard of sanitation services?
        rehabilitation_cost_owner:
          label: Who covers the cost of rehabilitation when larger repairs are needed (pit tank emptying)?
        supply_system_technologies:
          label: What are the typical household latrine types in your service delivery area?
          placeholder: Choose a technology
          tooltip: Only onsite household sanitation technologies are included at the moment.
        systems_number:
          label: How many latrines are there?
          placeholder: 5
          tooltip: This is used to calculate the cost of a single latrine
        system_population_design:
          label: How many people are these latrines designed to serve in total in this service area?
          placeholder: 20
          tooltip: Please use the (maximum) number of people that are expected to use the latrine type.
        system_population_actual:
          label: How many people do these latrines actually serve in total in this service area?
          placeholder: 30
          tooltip: Please use the (maximum) number of people that actually use the latrine type.
        aggregate_actual_hardware_expenditure:
          label: What is the total expenditure on capital hardware over the service area to construct the latrines? 
        actual_hardware_expenditure:
          label: What is the total capital expenditure hardware over the service area to construct the latrines?
          placeholder: 5000
          tooltip: "Capital 'hardware' investment in fixed assets, such as excavation, lining, slabs, superstructures and pipes."
        system_lifespan_expectancy:
          label: How long is the latrine expected to last from the time of construction (the useful lifespan)?
          placeholder: 30
          tooltip: Please provide the expenditure for the entire service area. If you only know an average cost per system then please multiply this by the number of systems.
        direct_support_cost:
          label: What has been spent/will be spent on expenditure on direct support?
          placeholder: 10
          tooltip: 'Please provide the expenditure per person per year. Direct support is structured support to service providers and users or user groups related to the operation and management of a WASH service; direct support costs are the costs of such support. They cover monitoring, technical advice and administrative, organisational or legal support.  The costs of support before and during the capital construction of a project are not included; they are considered to be capital software. Direct support is often used synonymously with “post-construction support”.'
        indirect_support_cost:
          label: What has been/will be the expenditure on indirect support?
          placeholder: 2
          tooltip: "Please provide the expenditure per person per year. Indirect support costs cover expenditure on this macro-level support, including planning and policy making, and support to decentralised service authorities or local government. Indirect support includes capacity building for professionals and technicians and capacity support to local government as service authorities, for example to adhere to national norms, standards and guidelines."
        annual_household_income:
          label: What is the average annual household income in the service area
          placeholder: 600
          tooltip: Quel est le revenu annuel moyen d'un ménage dans la zone de service?
        household_size:
          label: Average household size
          placeholder: 6
          tooltip: This is an approximation for household size used to calculate the affordability of the water services.
        actual_software_expenditure:
          label: What is the total expenditure on capital expenditure software over the service area during or prior to construction?
          placeholder: 3000
          tooltip: "Capital 'software' expenditure refers to work with stakeholders prior to construction or during implementation, such as community training, demand creation and hygiene promotion. Please provide the expenditure for the entire service area. If you only know an average cost per system then please multiply this by the number of systems."
       unpaid_labour:
          label: Has unpaid labour been contributed by the household or community to set up the onsite sanitation system?
          placeholder: Select an option
          tooltip: Please select an option
        minor_operation_expenditure:
          label: What is the minor operation and maintenance expenditure per year?  
          placeholder: 1000
          tooltip: "Operational and minor maintenance expenditure is the recurrent, regular and ongoing expenditure on chemicals, materials and cleaning products. Please provide the expenditure for the entire service area. If you only know an average cost per system then please multiply this by the number of systems."
        capital_maintenance_expenditure:
          label: What is the average capital maintenance expenditure per year?
          placeholder: 400
          tooltip: "Capital maintenance expenditures are the costs of renewing (replacing, rehabilitating, refurbishing, restoring) assets to ensure that services continue at the same level of performance that was first delivered. Examples include such as replacing a slab, emptying a septic tank or re-siting the latrine. As capital maintenance expenditure is by definition infrequent try, they may not occur annually, if you are using actual data look for the average expenditure over the last 5 years. Please provide the expenditure for the entire service area. If you only know an average cost per system then please multiply this by the number of systems."
        loan_cost:
          label: What is the cost servicing any loans taken to fund the service?
          placeholder: 6000
          tooltip: "Please provide the average expenditure required to pay for loans, e.g. interest payments. Please provide the expenditure for the entire service area. If you only know an average cost per system or household then please multiply this by the number of systems or households respectively."
        loan_payback_period:
          label: What is the payback period on this loan?
          placeholder: 20
          tooltip: Please provide the average length of time spent to payback the loans.
        service_levels:
          label: Please define up to four service levels for users of the sanitation service
          tooltip: Please define up to four service levels
        service_level_name:
          label: Name the service level
          placeholder: Service level name
        service_level_share:
          label: Service level share
          placeholder: 25%
        national_accessibility_norms:
          label: Does the service accessibility meet the national norms?
          placeholder: Select an option
          tooltip: Please select an option.
        national_use_norms:
          label: Does the service use meet the national norms?
          placeholder: Select an option
          tooltip: Please select an option.
        national_environmental_protection_norms:
          label: Does the service environmental protection meet the national norms?
          placeholder: Select an option
          tooltip: Please select an option.
        national_reliability_norms:
          label: Does the service reliability meet the national norms?
          placeholder: Select an option
          tooltip: Please select an option.
      report:
        final_report: Advanced Sanitation | Final Report